debug: true
host: 0.0.0.0
port: 8080
base_url: "http://localhost:8080"
database_url: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
migration_source: "file://internal/database/migrations"
